chore: tune GitHub workflow (#80)
* chore: tune GitHub workflow

* tests: getPackageDependencies cover by tests

diff --git a/.github/workflows/action_app_analyze.yaml b/.github/workflows/action_app_analyze.yaml
--- a/.github/workflows/action_app_analyze.yaml
+++ b/.github/workflows/action_app_analyze.yaml
@@ -5,14 +5,14 @@ on:
     branches:
       - main
     paths:
-      - "action_app/**"
       - ".github/workflows/action_app_analyze.yaml"
+      - "action_app/**"
   push:
     branches:
       - main
     paths:
-      - "action_app/**"
       - ".github/workflows/action_app_analyze.yaml"
+      - "action_app/**"
 
 env:
   INPUT_CHECK_UNUSED_FILES: true
@@ -38,13 +38,13 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Checkout
+        uses: actions/checkout@v2.4.0
+
       - name: Install Stable Dart
-        uses: dart-lang/setup-dart@v1
+        uses: dart-lang/setup-dart@v1.3
         with:
           sdk: "stable"
-
-      - name: Checkout
-        uses: actions/checkout@v2
 
       - name: Install dependencies
         run: dart pub get
@@ -73,13 +73,13 @@ jobs:
         working-directory: action_app
 
     steps:
+      - name: Checkout
+        uses: actions/checkout@v2.4.0
+
       - name: Install Stable Dart
-        uses: dart-lang/setup-dart@v1
+        uses: dart-lang/setup-dart@v1.3
         with:
           sdk: "stable"
-
-      - name: Checkout
-        uses: actions/checkout@v2
 
       - name: Install dependencies
         run: dart pub get
@@ -90,8 +90,18 @@ jobs:
         if: success()
         run: |
           dart test --coverage=coverage
+          mv reports/tests.json reports/original.json
           dart pub run coverage:format_coverage --packages=.packages -i coverage -o coverage/coverage.lcov --lcov --report-on=lib
           dart run tool/uncovered_coverage.dart
           dart test test/fake_test.dart --coverage=coverage
           dart pub run coverage:format_coverage --packages=.packages -i coverage -o coverage/coverage.lcov --lcov --report-on=lib
           bash <(curl -s https://codecov.io/bash) -f coverage/coverage.lcov -F action_app
+
+      - name: Publish test results
+        uses: dorny/test-reporter@v1.5.0
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: Tests result
+          path: action_app/reports/original.json
+          reporter: dart-json
+          token: ${{ secrets.GITHUB_TOKEN }}
